#!/usr/bin/perl
use strict;
use warnings;
 
# this script was included in the makedist.pl to generate the Examples.pod file
# every time building a new distribution.
# We should also make sure the file is included in the distribution and
# installed on the target machines.
  
# Written by Gabor Szabo <gabor@pti.co.il>
 
open my $out, ">lib/MikroTik/API/Examples.pod" or die "lib/MikroTik/API/Examples.pod: $!";
print $out <<END;

=encoding utf8

=head1 NAME
 
MikroTik::API::Examples - collection of the scripts from eg
 
=head1 Synopsis
 
This module was autogenerated from the files in the eg directory of
the distribution. For detailed (cough) documentation see L<MikroTik::API>.
To run the examples either copy-paste them from here or download and unpack
the distribution and take the files from the eg directory.
 
=head1 Examples
 
END
 
 
open(MAN, "<MANIFEST") or die "MANIFEST: $!";
my @manifest = <MAN>;
close(MAN);
 
foreach my $file (@manifest)  {
        chomp $file;
        next if $file !~ m{eg/(.*)\.pl};
        next if $1 eq 'make_eg';
 
        print $out "\n=head2 $file\n\n";
        open my $fh, "<", $file or die "$file: $!";
        my @lines = <$fh>;
        for ( @lines) {
                next if /^#\s*\$Id/;
                print $out "    $_";
        }
}
 
print $out <<END;

=cut
END